clinicjs/node-clinic-flame

analysis/frame-node.js, visualizer/flame-graph-frame.js, visualizer/flame-graph-label.js, visualizer/flame-graph.js, visualizer/info-box.js, visualizer/key.js, visualizer/style.css, visualizer/ui.js
Search results stopped highlighting in https://github.com/nearform/node-clinic-flame/commit/1aabfe74f41e454299ec71b8df9b105feb662e54 - previously, a default from d3-fg was relied upon for styling search results.
The first commit fixes that and applies a stable search style, highlighting matches by:
- On normal frames, reversing the colours, giving the background a bright white, blue or grey so that search matches stand out and can still be easily identified as app, deps or core
- On tiny frames, which were previously just a line tinted in the colour of app, deps or core, the tint is strengthened, resulting in the same visual effect - regardless of size, it stands out in that colour.
However, `showOptimisationStatus` previously worked using search, which gets broken by this change. That …
=> Show search results by reversing colours, and optimisation status by changing key

visualizer/flame-graph.js, visualizer/info-box.css, visualizer/info-box.js
Fixes a few cases where the display of the info bar looks wrong:
1. Removes the `flex-basis` that allocates more space to the file path than it necessarily needs:
Before:
After:
2. Replaces it with another way of sharing the text that gives file paths a consistent starting position except where an unusually long function name needs more space:
3. Fixes a small bug where if a selected frame is above the current scroll position, the dotted line is assigned an invalid negative height and therefore keeps whatever height it had before.
Before: 
After:
=> Fix info bar quirky cases

package.json, visualizer/flame-graph.js
On double-click the selected node gets zoomed in / out.
[Needs this PR to be merged](https://github.com/davidmarkclements/d3-fg/pull/26), will update package-json when this happens
=> zooming-in/out on dblClick

analysis/frame-node.js, test/analysis-categorise.test.js, test/analysis-target.test.js, visualizer/flame-graph-tooltip-container.js, visualizer/flame-graph.css, visualizer/flame-graph.js
Adds a tooltip button when hovering Node Core frames. Clicking it opens the function definition's on Github in a new tab.
=> Open Node Core links in the browser

visualizer/stack-bar.js
When all visible frames fit on the stack bar, there is no frame with a
`.remaining` property.
This fixes an issue where hovering the stack bar after toggling most
things off in the options menu would spew errors to the console.
=> Fix stack bar undefined property access when there are few frames

visualizer/stack-bar.js
The places that call `updateExclusions()` also already call `ui.draw()`,
in order to update the FlameGraph. That `.draw()` call also calls the
StackBar's `.draw()` method, so we don't need to do it in the
'updateExclusions' handler.
The StackBar is kinda expensive to update (can take about 30ms for a
single `.draw()` call) so it would be good to make it faster in the
future, but this will already save 50% so it's a good start :)
=> Prevent duplicate `draw()` call in StackBar

visualizer/flame-graph.js, visualizer/history.js, visualizer/search-box.js, visualizer/ui.js
When searching, the query is added to the hash as `&search=query here`. If the search query changes from something like `app` to `app.get`, it's assumed that the previous search was triggered while the user was still typing, and the hash is updated without creating a new history entry. This way you don't have to flick through a bunch of partial queries to go back in the history if you type slow.
This emits `search` and `clearSearch` events from UI so the SearchBox input can update, and moves the FlameGraph search() calls to also use those events.
=> Store search state in URL hash.

visualizer/options-menu.js
The `class="` attribute was never closed for these elements, causing
html parsing to fail, but not fail badly enough, so the links were
still visible, just didn't work.
=> Fix "More info" links in options menu

visualizer/flame-graph.js
`fg.cellHeight()` and `fg.width()` immediately rerender the graph, so
doing it unconditionally is quite expensive.
With this patch we rerender far less frequently, and an update just
causes 1 render instead of 3(!). If the size changed, we still do 2
renders, because of how d3-fg works … maybe we could use
`requestAnimationFrame` in d3-fg to batch updates, but that would
likely be a breaking change, and we rely on filter updates etc. being
processed synchronously in Flame.
=> Avoid rerendering flame graph if size hasn't changed

visualizer/options-menu.css, visualizer/options-menu.js
This prevents long code area descriptions from overflowing the
background colour, making text hard to read.
A `position:relative` wrapper div is used so the `<li>` boxes still
have the same size as before.
`position:absolute` allows the elements to overflow the `<li>` box, but
not the `<label>`; labels now have a solid background colour when hovered
so you can still read them (more or less) when they overflow.
Before:
After:
=> Make long descriptions appear over the next item on hover, fixes #25

README.md, collect/get-logging-paths.js, index.js, package.json, test/basic.test.js, test/cmd-dest.test.js, test/collect-get-logging-paths.test.js, visualizer/d3.js
This adds a `dest: 'path str'` option to Flame so the output location of the graphs and log data is configurable. With `dest: 'test-output-destination'`, files are placed in `test-output-destination/{pid}.clinic-flame`. This needed a change in `getLoggingPaths()`, that was already applied in clinic-common, so I figured this would be a good time to switch to clinic-common's implementation.
This requires https://github.com/nearform/node-clinic-common/pull/3 so clinic-common can support our Flame-specific files, tests pass with that patch.
=> Add --dest flag.

visualizer/selection-controls.js
A bug crept in where the number of frames was no longer reliably shown on initial load:
This fixes it:
=> Show frame count on initial load

visualizer/flame-graph.js, visualizer/ui.js
I found a couple of nasty bugs in setting the active tree based on the hash:
- Changing the tree to unmerged and then refreshing the page can cause errors because changing the tree from the hash simply changes the property without calling the datatree update chain. This changes it to use the existing `dataTree.setUseMergedTree()` method
- It's possible to then get timing errors due to the flamegraph trying to select or zoom a node from the wrong tree. This zooms out then clears the .selectedNode property while updating the tree
- There's also a potential timing error this fixes if a hash contains both a change from the default (merged) tree and changes to exclusions, because it tries to apply the exclusions to the wrong tree. This fixes that, too
=> Fix errors on applying unmerged tree from hash

visualizer/flame-graph-frame.js, visualizer/flame-graph.css, visualizer/info-box.css, visualizer/key.css, visualizer/options-menu.css, visualizer/selection-controls.css, visualizer/stack-bar.css, visualizer/style.css, visualizer/toolbar.css
This PR will be rebased when https://github.com/nearform/node-clinic-flame/pull/30 is merged, then after review changes etc, the plan is to release it in the same release. Current state is merged against latest https://github.com/nearform/node-clinic-flame/pull/30 and latest master (so this includes the bug fix in 3.2.1 / https://github.com/nearform/node-clinic-flame/pull/42 )
It does a few things:
- Makes presentation mode clearer on a projector in extreme conditions. Tested with a projector from further than the recommended distance in a room with bright daylight, see https://github.com/nearform/node-clinic-flame/pull/30#issuecomment-439799245 for photos and a screenshot
- Simplifies the general design a little outside of presentation mode:
- Dropping the grey borders around the buttons …
=> Design and presentation mode adjustments

analysis/index.js, visualizer/data-tree.js, visualizer/options-menu.css, visualizer/options-menu.js, visualizer/ui.js
Changes the list to:
Just added it as another filter option like before, since it will keep using the `dataTree.exclude` property anyway.
=> Simplify code area categories

visualizer/data-tree.js, visualizer/flame-graph.js, visualizer/info-box.js, visualizer/main.js, visualizer/no-data-node.js, visualizer/selection-controls.js, visualizer/stack-bar.js, visualizer/ui.js
Fixes https://github.com/nearform/node-clinic-flame/issues/16
Instead of hitting an error when a user hides all nodes, they get this view:
This fixes it by using a dummy node when the visible dataset is empty. This avoids the problem described by @goto-bus-stop in https://github.com/nearform/node-clinic-flame/issues/16 of many parts of the code expecting data and means we don't have to pepper the code with, for example,  `if (this.ui.dataTree.flatByHottest.length)` checks. 
There's always a selected node and at least one visible node in the data for everything to use: it just might be a 0-value dummy, identifiable by `type === 'no-data'` or `category === 'none'` (if we in future needed other types of dummy node), with `fileName` and `functionName` properties that put a message for the …
=> Fix errors if user hides all nodes 

package.json
We don't know exactly why we're failing on CITGM https://github.com/nearform/node-clinic-flame/issues/55 - but we've got some tests which can take ~25 seconds to run locally and on our CI, and given that Doctor has a problem with tests passing locally and on our CI but timing out on CITGM, it stands to reason that Flame is at risk of the same thing.
Smaller increase than the equivalent Doctor PR https://github.com/nearform/node-clinic-doctor/pull/197 because it's not explictly confirmed that we are timing out. As with that PR, a) higher limit when coverage is enabled, b) we should also try to make the slow tests faster.
=> Raise test timeout limits

analysis/frame-node.js, test/analysis-categorise.test.js, visualizer/flame-graph-label.js, visualizer/info-box.js, visualizer/key.js, visualizer/ui.js
While working on the relevant documentation, I realised the way these labels were worded was potentially slightly misleading. 
For example (this is with "Merge" unticked and "Show optimization status" ticked, see top right, bottom right, and on the flamegraph):
=> Reword labels of unmerged frames to be simply "Optimized" or "Unoptimized"

analysis/frame-node.js, package.json
Fixes https://github.com/nearform/node-clinic-flame/issues/58 ~but we should double-check again after that 0x PR https://github.com/davidmarkclements/0x/pull/203 lands.~ landed, released as 4.7.1, included in this PR.
Before (Node 10.13.0 profile generated on Windows):
After:
Both before and after look pretty much the same with and without https://github.com/davidmarkclements/0x/pull/203  branch of 0x, and same on Node 8 too.
=> Unescape escaped backslashes (\\u005c)

visualizer/info-box.css, visualizer/info-box.js, visualizer/style.css
Adds "line:X column:Y" to the text in the info box, like this:
- Explicitly says these are line and column numbers in full, because we've got space to follow the pattern of space-saving form on the flamegraph vs written more completely in the info box
- Written with colons (line:X column:Y) to complement the truncated form (:X:Y) used on the flamegraph
- Slightly darker than the path text with two spaces separating it, so the path is still visually one unit and still nice and clean and easy to read
- `white-space: nowrap` so that the line and column numbers stick together. So it wraps like this:
...not like this:
=> Add line/column numbers to info box paths

analysis/code-areas.js, analysis/index.js, test/analysis-dependencies.test.js, test/visualizer-history.js, visualizer/history.js, visualizer/ui.js
This still needs some styling work (a long dependency list overflows the page), probably more
Sample here:
https://upload.clinicjs.org/public/9bb3f6bd3acd7178b5cb8faa9590f6796859631213561522ba0b9c1391b67d59/5338.clinic-flame.html
Try toggling `async` or `bunyan` for some highly visible examples.
=> Collect dependencies as separate code areas.

visualizer/ui.js
Works in conjunction with this [website PR](https://github.com/nearform/clinicjs-website/pull/110) which should be merged first.
Simply updates the links to point to relevant section on Flame docs for advanced controls.
=> Implement new URLs to controls docs in more info links

package.json, visualizer/flame-graph.js
This works in unison with [this d3-fg PR](https://github.com/davidmarkclements/d3-fg/pull/29) to fix the issue with a floating flame graphs, by using a more appropriate minHeight.
Once [the d3-fg PR](https://github.com/davidmarkclements/d3-fg/pull/29) is merged, you'll need to generate a shallow stack by analysis and simple script to replicate the bug. With this branch linked to Clinic, it should generate a flame graph positioned at the bottom.
=> #52 - Ensure minHeight is set to graph container height

analysis/frame-node.js, analysis/index.js, package.json, test/visualizer-data-tree.test.js, visualizer/data-tree.js, visualizer/flame-graph-frame.js, visualizer/flame-graph-label.js, visualizer/flame-graph.css, visualizer/flame-graph.js, visualizer/ui.js
Needs this patch on d3-fg else there are small layout conflicts https://github.com/davidmarkclements/d3-fg/pull/30
This took a long time... I ran into a few dead ends and needed to start again with a completely new approach more than once, mostly around issues with sorting a D3 partition where you can have invisible intermediaries, and around the fact that we're displaying data that relates to more than one node, which runs into issues with the way the d3-fg canvas draws over itself. The best way I could find around these issues was to be not strict about the expected order of visible children, and to add another canvas overlay above the main canvas.
This PR outlines and labels code areas - one of the features in my original Flame design which seemed to work well in testing but wasn't …
=> Outline code area groupings

visualizer/info-box.css, visualizer/info-box.js, visualizer/selection-controls.css, visualizer/style.css, visualizer/toolbar.css
- Adds a dropdown inside the info box which displays stack percentages (top and overall)
- Centres text inside info box
- Stacks text inside info box on smaller screens with ability to scroll to see all text
- Adds titles to each text element inside info box in case of massive path or function string
https://upload.clinicjs.org/public/c748ff5b367a00825f2f8157d85d70c54402cf628b02faa5ca9437a92e63bcb3/49653.clinic-flame.html#selectedNode=207&zoomedNode=&exclude=8000&merged=true
https://upload.clinicjs.org/public/eb6802c7c59ef7005c46ae87e42d1d46fc7f2693bbeb099a8396ea945755c0e4/49653.clinic-flame.html#selectedNode=207&zoomedNode=&exclude=8000&merged=true
=> Flame graph percentage display

index.js, package.json
It's no longer being used now that clinic-common provides the icons!
=> Remove browserify-inline-svg

package.json
we use it in index.js.
(when using the Clinic CLI, it all works out, because rimraf is installed anyway. doing `npm install @nearform/flame` doesn't work though.)
=> move rimraf to dependencies

analysis/code-areas.js, analysis/frame-node.js, package.json, test/analysis-categorise.test.js, test/basic.test.js, test/fixtures/wasm.js, visualizer/filters-bar.css, visualizer/filters-bar.js, visualizer/flame-graph-label.js, visualizer/ui.js
Depends on https://github.com/davidmarkclements/0x/pull/218
Example: https://upload.clinicjs.org/public/9f949dda1c7a611cc6cb4a270e7793dc75d205c508605b761b88fd91000e9f16/463707.clinic-flame.html#selectedNode=678&zoomedNode=678&exclude=8fff-ef00&merged=true
Code used for example: test suite from https://github.com/goto-bus-stop/require-detective
This fixes a crash on WebAssembly stack frames. WASM frames are now treated as a separate category, next to App/Deps/Core/V8.
One thing that may be worth a shot in the future is to categorise wasm and eval frames based on their parent frame. If the parent is in a dependency, the wasm is likely part of that dependency (most<sup>[citation needed]</sup> wasm modules ship with a commonjs wrapper in the same npm package anyways). A possible argument …
=> Basic WebAssembly support

visualizer/ui.js
Issue:
"Bottom left corner is not the most common place for help. Top right corner is more frequent."
Fix:
Moved to top right. Some styling of the button will also be required.
=> Move Help button to top right

visualizer/style.css
Issue:
"Gray text on black background unreadable."
Fix:
Keep grey colour to differ from app label (white) but make it lighter to increase contrast.
Before:
After:
=> Tweak colour of core label to lighter grey

visualizer/flame-graph.css
Issue:
"Shadow makes content below unreadable."
Fix:
Keep the linear gradient but make it light coloured to improve text contrast. 
Before:
After:
=> Change dark shadow into a light shadow for improved contrast

index.js, package.json
Pass the tool version to the html template.
[Issue FK02](https://trello.com/c/vgIgBXME/843-fk02-visibility-of-system-status)
=> Display flame version beneath logo

visualizer/style.css
Issue:
"Blue text on black is not readable."
Fix:
Change blue to "flame orange". This improves the text readability and also matches in with the app colour scheme.
Before:
After:
=> Improve contrast of graph label text

visualizer/message.css
Changed the colour from green to flame logo orange to make the colour scheme more consistent
Before:
After:
[Issue FD02](https://trello.com/c/18XBhckv/831-fd02-consistency-and-standards)
=> Change copied-to-clipboard message colour

visualizer/ui.js
`npm run test` was failing at line 635 `d3.select('.nc-header...`
=> add d3-selection module loading

visualizer/ui.js
Issue:
Eyes are drawn to the NearForm logo although it is a secondary element in terms of hierarchy.
Fix:
1. Remove the Nearform logo from the header. https://github.com/nearform/node-clinic-common/pull/24 (Merged)
2. This PR will put the logo in the bottom left. Since https://github.com/nearform/node-clinic-flame/pull/115 created the space required. (Merged)
~~Recommended to merge https://github.com/nearform/node-clinic-flame/pull/115 before this one.~~ (Merged)
Position of logo will be adjusted via:
https://github.com/nearform/node-clinic-common/pull/29
=> Put Nearform logo in bottom left

visualizer/walkthrough-steps.js
Add a bit of information letting the user know about the double click to expand function on function blocks.
[Relates to FB02](https://trello.com/c/06IWR6Jo/822-fb02-flexibility-and-efficiency-of-use)
[Additional issue on Trello this relates to](https://trello.com/c/8iYqGeYa/724-new-tooltip-menu-make-double-clicking-into-a-frame-more-intuitive)
https://github.com/nearform/node-clinic-flame/issues/86
=> add additional info to walkthrough

visualizer/filters-content.css, visualizer/filters-content.js
Currently you can still toggle "Show optimization status" even if "Merge" option is checked. The UI should reflect that these options cannot be used together.
The checkbox for "Show optimization status" will be disabled if "Merge" option is checked. Also may look to:
- Improve disabled style.
- Provide a tooltip to describe why the option is disabled.
=> Enabling optimization status doesn't make any sense on merged tree

.github/workflows/ci.yml
Well, this is a simple one but I think it's worth adding node 14 to the GitHub ci workflow.
I've tested it locally and all tests are green.
=> Add node 14 to ci workflow

README.md, analysis/frame-node.js, index.js, package.json, test/analysis-categorise.test.js, test/basic.test.js
This PR adds support to `kernel-tracing` through 0x.
* fixes optimization flag
* add kernelTracing option
* drop support to node v10 or prior (0x minimum is v12 at v5)
* bump 0x to v5
=> feat: add kernelTracing option

analysis/frame-node.js, test/analysis-label-nodes.test.js
Address: https://github.com/clinicjs/node-clinic/issues/327﻿
Unfortunately, this is the only thing that we can do from clinicjs/0x side.
It's expected to see `foo\bar` in the call stack, however, the `--prof-process` doesn't parse it properly transforming it into: `~foo\nhome/clinic/clinic-327.js:2:13 [INIT]`.
So, in that situation, the users will see `foo` instead of `foo\bar` in the call-stack.
=> fix: replace newline escaped to backslashes

index.js
Depends on https://github.com/clinicjs/node-clinic/pull/399
=> feat: accept logging path name as identifier
